### ISSUE TITLE
Clearing Database or Time Series Data

### ISSUE THREAD

**Issue by dirkduplooy** [pedrocesar-ti/internet-speedtest-docker#17]
Hi I started to use the docker, but I had unintended downtime on my link, how do I clear the database or the time series, I looked at InfluxDB documentation, but I also cannot reach the DB management console via port 8083, it is installed on Ubuntu Server 18.04.3 LTS, Thank you

**Comment by pedrocesar-ti** [comment]
Hey @dirkduplooy,

If you want to start the whole thing fresh, you can just remove the datadir (influxDB) persistent data and restart the docker-compose (BUT REMEMBER IF YOU REMOVE THE DATADIR YOU WILL LOSE ALL DATA).

I just learned that InfluxDB removed access to the WebAdmin management console on version 1.3.
https://docs.influxdata.com/chronograf/v1.7/administration/transition-web-admin-interface/
- So I will remove the port mapping for 8083.

But you can still use the API to run the queries, including DROP on the time series, here is one example:

![Screen Shot 2019-09-23 at 07 19 41](https://user-images.githubusercontent.com/9018178/65393359-b372e480-ddd3-11e9-9155-64f36703c438.png)

or cURL:
`curl -XPOST 'http://localhost:8086/query?pretty=true' --data-urlencode "db=speedtest" --data-urlencode "q=DROP SERIES FROM \"download\""`


![Screen Shot 2019-09-23 at 07 26 29](https://user-images.githubusercontent.com/9018178/65393340-845c7300-ddd3-11e9-96f4-2ad3ba35bd36.png)

P.S.: Just out of curiosity, why would you want to clear the time series? 

Hope that helps!

**Comment by dirkduplooy** [comment]
Hi Pedro, the cURL command does not seem to work  "error": "missing required parameter \"q\"". I did the initial test of this long-distance WIFI link but played around with the settings of the receiver in order to get it as optimal as possible which obviously created prolonged outages, want to reset and restart while the link is "stable"

**Comment by pedrocesar-ti** [comment]
Hey @dirkduplooy,

Can you access (ssh) in to the box (where the docker containers are running)?

**Comment by pedrocesar-ti** [comment]
Sorry man, I think I missed your point, but if you got access to the machine you can also connect to the container and perform all the drops manually.

**Comment by dirkduplooy** [comment]
Hi Pedro I am reinstalling on a new image, in order to get things "straight", if I have another issue I will let you know

**Comment by dirkduplooy** [comment]
Hi Pedro I am reinstalling on a new image, in order to get things "straight", if I have another issue I will let you know
