### ISSUE TITLE
Updated Speedtest Docker Image

### ISSUE THREAD

**Issue by phikai** [pedrocesar-ti/internet-speedtest-docker#7]
Just wanted to drop you a quick note and say THANK YOU for your work on this image. It's greatly inspired me for a couple of other projects... one of which you may want to port back over.

I've created an updated Speedtest Docker image based on Alpine and using `pip` to install the speedtest-cli package: https://github.com/phikai/docker-speedtest

I've also created a "clone" of your project using Chronograf (instead of Grafana... for latest version, but not as nicely auto configured) and my version of the speedtest image: https://github.com/phikai/docker-internet-speedtest-dashboard

In either case... thanks! and let me know if you have any concerns.

**Comment by pedrocesar-ti** [comment]
Sure man, happy to help :) much appreciate the contact and let me know if you need anything!

**Comment by gotskeet** [comment]
Hello!

I am interested in having this set on my syno but i must admit, i cannot replicate all the steps. Would you have the time to share some steps for dummies?
