### ISSUE TITLE
Datasource named InfluxDB was not found

### ISSUE THREAD

**Issue by Rahulsharma0810** [pedrocesar-ti/internet-speedtest-docker#8]
I am getting "Datasource named InfluxDB was not found" On my Locally machine after login to grafana 
account.
Local ip is : 192.168.0.52:3000

![image](https://user-images.githubusercontent.com/9934859/48969334-3d6ee700-f023-11e8-96fb-0fdb637c0724.png)

**Comment by pedrocesar-ti** [comment]
Hi Rahul sharma,

I just ran a quick test and apparently there is an issue with the latest InfluxDB Docker Image. I'll be creating a fix for that soon.

At the moment a simple workaround is to change the InfluxDB tag (maybe version 1.6.4) on the docker-compose file.
` db:
      image: influxdb:1.6.4
      container_name: influxdb
      volumes:
        - "./data/influxdb/:/var/lib/influxdb"
      ports:
        - "8083:8083"
        - "8086:8086"
      env_file:
        - ./env/db.env`

**Comment by pedrocesar-ti** [comment]
Everything looks good now.
